---

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present


- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'


- name: Create users
    user:
      name: "{{ item.name }}"         
      groups: "{{ item.name }}"
      createhome: yes
      append: yes
      state: present
    with_items: "{{ user_details }}"


- name: Set up authorized keys for the user
  authorized_key: 
    user: "{{ user_name }}" 
    key: "{{ item }}"
  with_file:
    - /id_awx.pub
